config:
  COM_PORT: AUTO
  THEME: Advanced Radials Test
  HW_SENSORS: AUTO
  ETH: throne-tun
  WLO: ''
  CPU_FAN: amdgpu/fan1
  PING: 8.8.8.8
  WEATHER_API_KEY: ''
  WEATHER_LATITUDE: 45.75
  WEATHER_LONGITUDE: 4.85
  WEATHER_UNITS: metric
  WEATHER_LANGUAGE: en
display:
  REVISION: A_HID
  BRIGHTNESS: 20
  DISPLAY_REVERSE: false
  RESET_ON_STARTUP: true
  SMARTMONITOR_HID_RUNTIME: true
  SMARTMONITOR_HID_THEME_FILE: /home/lord/Документы/PROJECT CODEX/turing-smart-screen-python-main/res/themes/rog03-compiled.dat
  SMARTMONITOR_HID_UPLOAD_ON_START: false
  SMARTMONITOR_HID_SEND_TIME: false
  SMARTMONITOR_HID_CMD: 2
  SMARTMONITOR_HID_UPDATE_INTERVAL: 2
  SMARTMONITOR_HID_TIME_INTERVAL: 1
  SMARTMONITOR_HID_TAGS:
    CPU_TEMP: 1
    GPU_TEMP: 5
    RAM_PERCENT: 12
